export const HELMET_DEFAULT_HEADERS: Readonly<Map<string, string>> = new Map([
	['Cache-Control', 'no-store, max-age=0'],
	['Cross-Origin-Embedder-Policy', 'require-corp'],
	['Cross-Origin-Opener-Policy', 'same-origin'],
	['Cross-Origin-Resource-Policy', 'same-origin'],
	['Expect-CT', 'max-age=86400, enforce'],
	['Expires', '0'],
	['Origin-Agent-Cluster', '?1'],
	['Pragma', 'no-cache'],
	['Referrer-Policy', 'no-referrer'],
	['Strict-Transport-Security', 'max-age=15552000; includeSubDomains; preload'],
	['Timing-Allow-Origin', 'same-origin'],
	['X-Content-Type-Options', 'nosniff'],
	['X-DNS-Prefetch-Control', 'off'],
	['X-Download-Options', 'noopen'],
	['X-Frame-Options', 'SAMEORIGIN'],
	['X-Permitted-Cross-Domain-Policies', 'none'],
	['X-XSS-Protection', '1; mode=block'],
])

export const HELMET_CSP_HEADER: Readonly<Record<string, string>> = Object.freeze({
	'default-src': "'self'",
	'script-src': "'self'",
	'script-src-attr': "'none'",
	'style-src': "'self' https: 'unsafe-inline'",
	'img-src': "'self' data:",
	'connect-src': "'none'",
	'font-src': "'self' https: data:",
	'object-src': "'none'",
	'media-src': "'none'",
	'frame-src': "'none'",
	'sandbox': 'allow-forms allow-same-origin',
	'report-uri': '/api/v0/csp/report',
	'child-src': "'none'",
	'form-action': "'self'",
	'frame-ancestors': "'self'",
	'base-uri': "'self'",
	'report-to': '/api/v0/csp/report',
	'worker-src': "'none'",
	'manifest-src': "'self'",
	'upgrade-insecure-requests': '',
})

export const HELMET_PERMISSIONS_POLICY_HEADER: Readonly<string> = ''
