export const SENTINEL_DEFAULT_HEADERS: Readonly<Map<string, string>> = new Map([
	['Cache-Control', 'no-store, max-age=0'],
	['Cross-Origin-Embedder-Policy', 'require-corp'],
	['Cross-Origin-Opener-Policy', 'same-origin'],
	['Cross-Origin-Resource-Policy', 'same-origin'],
	['Expect-CT', 'max-age=86400, enforce'],
	['Expires', '0'],
	['Origin-Agent-Cluster', '?1'],
	['Pragma', 'no-cache'],
	['Referrer-Policy', 'no-referrer'],
	['Timing-Allow-Origin', 'same-origin'],
	['X-Content-Type-Options', 'nosniff'],
	['X-DNS-Prefetch-Control', 'off'],
	['X-Download-Options', 'noopen'],
	['X-Frame-Options', 'SAMEORIGIN'],
	['X-Permitted-Cross-Domain-Policies', 'none'],
	['X-XSS-Protection', '1; mode=block'],
	['X-Dark-Net', '?1'],
])

export const SENTINEL_CSP_DIRECTIVES: Readonly<Record<string, string>> = Object.freeze({
	'default-src': "'none'",
	'script-src': "'none'",
	'script-src-attr': "'none'",
	'style-src': "'self'",
	'img-src': "'self'",
	'connect-src': "'none'",
	'font-src': "'none'",
	'object-src': "'none'",
	'media-src': "'none'",
	'frame-src': "'none'",
	'sandbox': 'allow-forms allow-same-origin',
	'report-uri': '/api/v0/csp/report',
	'child-src': "'none'",
	'form-action': "'self'",
	'frame-ancestors': "'none'",
	'base-uri': "'self'",
	'report-to': '/api/v0/csp/report',
	'worker-src': "'none'",
	'manifest-src': "'self'",
})

export const SENTINEL_PERMISSIONS_POLICY: Readonly<string> = [
	'accelerometer=()',
	'autoplay=()',
	'camera=()',
	'cross-origin-isolated=()',
	'display-capture=()',
	'encrypted-media=()',
	'fullscreen=()',
	'geolocation=()',
	'gyroscope=()',
	'keyboard-map=()',
	'magnetometer=()',
	'microphone=()',
	'midi=()',
	'payment=()',
	'picture-in-picture=()',
	'publickey-credentials-get=()',
	'screen-wake-lock=()',
	'sync-xhr=()',
	'usb=()',
	'web-share=()',
	'xr-spatial-tracking=()',
].join(', ')
