// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_views_home_layout from './routes/(views)/(home)/_layout.tsx'
import * as $_views_home_index from './routes/(views)/(home)/index.tsx'
import * as $_app from './routes/_app.tsx'
import * as $_middleware from './routes/_middleware.ts'
import * as $api_v0_csp_report from './routes/api/v0/csp/report.ts'
import * as $index from './islands/index.tsx'
import type { Manifest } from '$fresh/server.ts'

const manifest = {
	routes: {
		'./routes/(views)/(home)/_layout.tsx': $_views_home_layout,
		'./routes/(views)/(home)/index.tsx': $_views_home_index,
		'./routes/_app.tsx': $_app,
		'./routes/_middleware.ts': $_middleware,
		'./routes/api/v0/csp/report.ts': $api_v0_csp_report,
	},
	islands: {
		'./islands/index.tsx': $index,
	},
	baseUrl: import.meta.url,
} satisfies Manifest

export default manifest
